inputs:
  port:
    description: 'Specify port for node application to run'
    default: 1010
  environment:
    description: 'Environment for sample node application'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started..
      shell: powershell
    - name: echo Install de
      working-directory: tests
      run: pip install -r requirements.txt
      shell: powershell
    - name: Delete service
      shell: bash
      working-directory: tests
      run:  pm2 delete greetings-app-${{ inputs.environment }} ; if ($LASTEXITCODE -eq 100) { $true }
#    - name: Delete service
#      run: pm2 start -n "books-${{ inputs.environment }}" index.js -- ${{ inputs.port }}