inputs:
  port:
    description: 'Specify port for node application to run'
    default: 7000
  environment:
    description: 'Environment for sample node application'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started..
      shell: powershell
    - name: echo Install de
      working-directory: deploy
      run: pip install -r requirements.txt
      shell: powershell
    - name: Delete service
      shell: powershell
      working-directory: deploy
      continue-on-error: true
      run: pm2 delete greetings-app-${{ inputs.environment }}; if ($LASTEXITCODE -eq 100) { $true }
    - name: Start service
      shell: cmd
      working-directory: deploy
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{inputs.port}}