# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      run: echo Install Python dependencies!
  deploy-to-dev:
    runs-on: self-hosted
    steps:
      run: echo Deploying to DEV...
    needs: install-pip-deps
  tests-on-dev:
    runs-on: self-hosted
    steps:
      run: echo Running tests on DEV...
    needs: [ install-pip-deps,deploy-to-dev ]
  deploy-to-staging:
    runs-on: self-hosted
    steps:
      run: echo Deploying to STAGING
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev ]
  tests-on-staging:
    runs-on: self-hosted
    steps:
      run: echo Running tests on STAGING
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev,deploy-to-staging ]
  deploy-to-preprod:
    runs-on: self-hosted
    steps:
      run: echo Deploying on PRE_PROD
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev,deploy-to-staging,tests-on-staging ]
  tests-on-preprod:
    runs-on: self-hosted
    steps:
      run: echo Running tests on PRE_PROD
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev,deploy-to-staging,tests-on-staging,deploy-to-preprod ]
  deploy-to-prod:
    runs-on: self-hosted
    steps:
      run: echo Deploying to PROD
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev,deploy-to-staging,tests-on-staging,deploy-to-preprod,
             tests-on-preprod ]
  Tests-on-prod:
    runs-on: self-hosted
    steps:
      run: echo Running tests on PROD
    needs: [ install-pip-deps,deploy-to-dev, tests-on-dev,deploy-to-staging,tests-on-staging,deploy-to-preprod,
             tests-on-preprod,deploy-to-prod ]

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
